name: PR Build Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vite-build:
    name: Vite Build Check
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🟩 Setup Node.js and PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8 # or your preferred pnpm version

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # or match your project's Node version
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔨 Build Vite App
        id: vite_build
        run: |
          echo "🔍 Starting Vite build..."
          if pnpm build; then
            echo "✅ Vite build completed successfully."
            echo "build_status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Vite build failed. Please check the logs above."
            echo "build_status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: ✅ Output Result
        if: success()
        run: |
          echo "🎉 Build succeeded and no errors were found."

      - name: ❌ Output Result
        if: failure()
        run: |
          echo "🚨 Build failed. Please check the output and fix the issue."

      - name: 💬 Comment on PR tagging repo owner and PR author
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get PR info
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const prAuthor = pr.data.user.login;
            // Get repo owner
            const repoOwner = context.repo.owner;
            // Compose comment
            const message = `✅ Vite build passed!\n\nThanks @${prAuthor} for your contribution!\n@${repoOwner}, this PR is ready for review.`;
            // Post comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });

      - name: 💬 Comment on PR about build failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get PR info
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const prAuthor = pr.data.user.login;
            // Get repo owner
            const repoOwner = context.repo.owner;
            // Compose comment
            const message = `❌ Vite build failed!\n\n@${prAuthor}, please check the build logs and fix the issues.\n@${repoOwner}, this PR needs attention.`;
            // Post comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });
